export const language = [{ //Словарь для локализации TODO:Redux 
  questions: 'Вопросы', 
  about: 'О нас', 
  сontacts: 'Контакты', 
  search: 'Поиск', 
  sections: 'Разделы', 
  programming:'Программирование', 
  other: 'Остальные вопросы', 
  cooking: 'Готовка', 
  diy: 'Сделай сам', 
  lifehacks: 'Лайфхаки', 
  topicks: 'Актуальные темы', 
  ask: 'Задать вопрос', 
  related:'Связанные теги', 
  mail: 'Почта', 
  sign: 'Войти', 
  register: 'Регистрация', 
  password:'Введите пароль', 
  confirmPassword:'Повторите пароль', 
  changePassword:'Изменить пароль', 
  oldPassword:'Старый пароль', 
  send:'Отправить' 
}, 
{ 
  questions: 'Questions', 
  about: 'About us', 
  сontacts: 'Contacts', 
  search: 'Search', 
  sections: 'Sections', 
  programming:'Programming', 
  other: 'Other help', 
  cooking: 'Cooking', 
  diy: 'DIY', 
  lifehacks: 'Lifehacks', 
  topicks: 'Topics of concern to the people', 
  ask: 'Ask question', 
  related:'Related Tags', 
  mail: 'Gmail', 
  sign: 'Sign In', 
  register: 'Registration', 
  password:'Password', 
  confirmPassword:'Confirm password', 
  changePassword:'Change Password', 
  oldPassword:'Old password', 
  send:'Send' 
}]

